exclude: |
  (?x)^(
    .idea/.*|
  )$

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.18
    hooks:
      - id: uv-lock

  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    # https://pypi.org/project/pre-commit-update/
    rev: v0.6.1
    hooks:
      - id: pre-commit-update

  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.29.0
    # Advanced refactorings for Python.
    # Hide it if you can't use it.
    hooks:
      - id: sourcery
        # The best way to use Sourcery in a pre-commit hook:
        # * review only changed lines:
        # * omit the summary
        #  args: [ --diff=git diff HEAD, --no-summary, --fix ]
        args: [--no-summary, --fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    # A collection of git hooks.
    hooks:
      - id: trailing-whitespace
        # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
        #      - id: end-of-file-fixer
        #        # Makes sure files end in a newline and only a newline.
        #        # Exclude some autogenerated files.
        #        exclude: |
        #          (?x)^(
        #            uv.lock|
        #            requirements.*.txt
        #          )$
      - id: check-yaml
        # Checks that your YAML files are parseable.
      - id: check-toml
        # Attempts to load all TOML files to verify syntax.
      - id: debug-statements
        # Check for debugger imports
      - id: check-added-large-files
        # Prevent giant files from being committed.
        args: [--maxkb=500]
  #      - id: no-commit-to-branch
  #        # No commits to master or main.
  #        args: [--branch=master, --branch=main]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    # Opinionated Code Formatter. For JS, CSS, Markdown, JSON, YAML and more.
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    # Static type checker for Python.
    hooks:
      - id: mypy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.1
    hooks:
      - id: ruff
        # Run the linter with unsafe fixes.
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
        # Run the formatter.

  - repo: https://github.com/Alirex/pre-commit-just
    # Justfile formatter.
    rev: "v0.2.1"
    hooks:
      - id: format-justfile
