#volumes:
#  files_input: { }
#  files_output: { }
#  logs: { }

services:
  app:
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
      - ./logs:/wd/logs:rw
      #      - files_input:/wd/files_input:ro
      #      - files_output:/wd/files_output:rw
      #      - logs:/wd/logs:rw
    env_file:
      - .env

    environment:
      project_workdir: ${project_workdir:-/wd}

    user: "${user_id:-1000}"
